### ISSUE TITLE
Invalid Date

### ISSUE THREAD

**Issue by Naoray** [CoreProc/nova-notification-feed#7]
![image](https://user-images.githubusercontent.com/10154100/53861826-95839500-3fe5-11e9-8862-2a03a9a3aa9e.png)

Changing the following lines in `NotificationMessage.vue` component resolves the issue.

```js
NotificationMessage.vue

// showing invalid date
fromNow (date) {
    return new moment.tz(date.date, 'YYYY-MM-DD HH:mm:ss', date.timezone).local().fromNow()
}

// working
      fromNow (date) {
            return new moment(date, 'YYYY-MM-DD HH:mm:ss').local().fromNow()
      }
```

**Comment by chrisbjr** [comment]
I see.. I think this issue relates to Laravel 5.8 not returning Date objects by default in APIs for created_at and updated_at anymore...

**Comment by chrisbjr** [comment]
Confirmed.

Here is the response in Laravel 5.7:

<img width="396" alt="date-57" src="https://user-images.githubusercontent.com/571279/53927309-6a6e7380-40c1-11e9-89e8-df7926c6b596.png">

After updating to Laravel 5.8, the response changes to this:

<img width="405" alt="date-58" src="https://user-images.githubusercontent.com/571279/53927323-78bc8f80-40c1-11e9-8fcb-638b2ed10afd.png">

**Comment by chrisbjr** [comment]
Fixed and tagged as `1.2.0`

**Comment by skoyah** [comment]
I have the latest version of the package and the issue persists.
